[package]
name = "price-service-client"
version = "0.1.0"
authors = ["Pyth Data Foundation"]
edition = "2021"
homepage = "https://pyth.network"
repository = "https://github.com/pyth-network/pyth-crosschain/"
description = "Pyth Hermes Client"
keywords = [ "pyth", "oracle" ]

[dependencies]
chrono = "0.4.38"
hermes = { path = "../../server" }
pyth-sdk = { git = "https://github.com/pyth-network/pyth-sdk-rs", version = "0.8.0" }
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.39.1", features = ["full"] }
url = "2.5.2"
